package com.example.study.model;

public class DoctorUser {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctor_user.id
     *
     * @mbg.generated Thu Mar 26 10:39:18 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctor_user.username
     *
     * @mbg.generated Thu Mar 26 10:39:18 CST 2020
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctor_user.password
     *
     * @mbg.generated Thu Mar 26 10:39:18 CST 2020
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctor_user.access_token
     *
     * @mbg.generated Thu Mar 26 10:39:18 CST 2020
     */
    private String accessToken;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctor_user.is_auth
     *
     * @mbg.generated Thu Mar 26 10:39:18 CST 2020
     */
    private Integer isAuth;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctor_user.id
     *
     * @return the value of doctor_user.id
     *
     * @mbg.generated Thu Mar 26 10:39:18 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctor_user.id
     *
     * @param id the value for doctor_user.id
     *
     * @mbg.generated Thu Mar 26 10:39:18 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctor_user.username
     *
     * @return the value of doctor_user.username
     *
     * @mbg.generated Thu Mar 26 10:39:18 CST 2020
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctor_user.username
     *
     * @param username the value for doctor_user.username
     *
     * @mbg.generated Thu Mar 26 10:39:18 CST 2020
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctor_user.password
     *
     * @return the value of doctor_user.password
     *
     * @mbg.generated Thu Mar 26 10:39:18 CST 2020
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctor_user.password
     *
     * @param password the value for doctor_user.password
     *
     * @mbg.generated Thu Mar 26 10:39:18 CST 2020
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctor_user.access_token
     *
     * @return the value of doctor_user.access_token
     *
     * @mbg.generated Thu Mar 26 10:39:18 CST 2020
     */
    public String getAccessToken() {
        return accessToken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctor_user.access_token
     *
     * @param accessToken the value for doctor_user.access_token
     *
     * @mbg.generated Thu Mar 26 10:39:18 CST 2020
     */
    public void setAccessToken(String accessToken) {
        this.accessToken = accessToken == null ? null : accessToken.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctor_user.is_auth
     *
     * @return the value of doctor_user.is_auth
     *
     * @mbg.generated Thu Mar 26 10:39:18 CST 2020
     */
    public Integer getIsAuth() {
        return isAuth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctor_user.is_auth
     *
     * @param isAuth the value for doctor_user.is_auth
     *
     * @mbg.generated Thu Mar 26 10:39:18 CST 2020
     */
    public void setIsAuth(Integer isAuth) {
        this.isAuth = isAuth;
    }
}