package com.example.study.mapper;

import com.example.study.model.DoctorUser;
import java.util.List;

public interface DoctorUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doctor_user
     *
     * @mbg.generated Thu Mar 26 10:39:18 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doctor_user
     *
     * @mbg.generated Thu Mar 26 10:39:18 CST 2020
     */
    int insert(DoctorUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doctor_user
     *
     * @mbg.generated Thu Mar 26 10:39:18 CST 2020
     */
    DoctorUser selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doctor_user
     *
     * @mbg.generated Thu Mar 26 10:39:18 CST 2020
     */
    List<DoctorUser> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doctor_user
     *
     * @mbg.generated Thu Mar 26 10:39:18 CST 2020
     */
    int updateByPrimaryKey(DoctorUser record);
}